version: '2'
services:
  atom:
    image: jamesnetherton/docker-atom-editor:v1.11.2
    environment:
      DISPLAY:
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./atom-config:/home/atom/.atom
      - /dev/shm:/dev/shm

  mysql-workbench:
    #unfortunately i couldn't find a image with other tags than latest, but that one serves the purpose of an example
    image: jdecool/mysql-workbench
    environment:
      DISPLAY:
    volumes:
      - ./mysqlwb-config:/root/.mysql/workbench
      - /tmp/.X11-unix:/tmp/.X11-unix
